require("../config/db.configuration");

const { Trail, Review } = require("../models")

const trails = [
    {
        name: 'Torres Del Paine "W" Circuit',
        description: "A long trek through the wilds of Chilean Patagonia, this trail is a famous route that features mountains, galciers, lakes, and exotic plant life. ",
        location: "Torres Del Paine, Patagonia",
        length: 43.1,
        elevation: 8956,
        style: "Out & Back",
        difficulty: 5,
        image: "https://i.imgur.com/tkWtYEv.jpg",
    },
    {
        name: "Edwards Point",
        description: "A woodsy hike out to a scenic view of the river. There is a quaint creek and blue hole area part way into the hike which is great for a swim in the summer.",
        location: "Signal Mountain, TN",
        length: 4.2,
        elevation: 550,
        style: "Out & Back",
        difficulty: 2,
        image: "https://i.imgur.com/N50VDOX.jpg",
    },
    {
        name: "Trolltunga",
        description: "A grueling hike to an iconic overhanging rock in the fjords of Norway",
        location: "Norway",
        length: 18.9,
        elevation: 4000,
        style: "Out & Back",
        difficulty: 5,
        image: "https://i.imgur.com/u2DdFSx.jpg",
    },
    {
        name: "Alum Cave to Mount LeConte",
        description: "A scenic uphill trek through the Smoky Mountains",
        location: "Smoky Mountains National Park",
        length: 11,
        elevation: 3000,
        style: "Out & Back",
        difficulty: 4,
        image: "https://i.imgur.com/CkrbxU9.jpg",
    },
    {
        name: "Devil's Garden",
        description: "A famous hike through scenic Arches",
        location: "Arches National Park",
        length: 7.9,
        elevation: 1006,
        style: "Loop",
        difficulty: 3,
        image: "https://i.imgur.com/47YZn5r.jpg",
    },
    {
        name: "Eibsee Loop",
        description: "Eibsee Loop is a 4.3 mile heavily trafficked loop trail located near Grainau, Bavaria, Germany that features a lake and is good for all skill levels. The trail is primarily used for hiking and walking and is best used from May until October.",
        location: "Bavaria, Germany",
        length: 4.3,
        elevation: 705,
        style: "Loop",
        difficulty: 2,
        image: "https://i.imgur.com/ltTZBX6.jpg",
    },
    {
        name: "Everest Base Camp Trek",
        description: "Everest Base Camp Trek is a 64.2 mile heavily trafficked out and back trail located near Khumjung, Province 1, Nepal that offers scenic views and is only recommended for very experienced adventurers. The trail is primarily used for hiking, camping, and backpacking and is best used from February until October. Dogs are also able to use this trail.",
        location: "Bhutan, Nepal",
        length: 64.2,
        elevation: 21322,
        style: "Out & back",
        difficulty: 5,
        image: "https://https://cdn.britannica.com/17/83817-050-67C814CD/Mount-Everest.jpg.imgur.com/ltTZBX6.jpg",
    },
    {
        name: "The Cliffs, Mount Bond and West Bond",
        description: "The Cliffs, Mount Bond and West Bond is a 21.6 mile heavily trafficked out and back trail located near Bethlehem, New Hampshire that offers the chance to see wildlife and is rated as difficult. The trail is primarily used for hiking, running, and backpacking and is best used from April until October. Dogs are also able to use this trail but must be kept on leash.",
        location: "White Mountains, NH",
        length: 21.6,
        elevation: 6751,
        style: "Out & back",
        difficulty: 4,
        image: "https://cdn-assets.alltrails.com/uploads/photo/image/39131393/extra_large_7186b5c1b56647213adf28fe8dd8477b.jpg",
    },
    {
        name: "Mount Lafayette and Franconia Ridge Trail Loop",
        description: "Mount Lafayette and Franconia Ridge Trail Loop is a 9.3 mile heavily trafficked loop trail located near Lincoln, New Hampshire that features a waterfall and is only recommended for very experienced adventurers. The trail is primarily used for hiking and snowshoeing and is best used from April until October. Dogs are also able to use this trail.",
        location: "White Mountains, NH",
        length: 9.3,
        elevation: 3809,
        style: "Loop",
        difficulty: 4,
        image: "https://cdn-assets.alltrails.com/uploads/photo/image/41425469/extra_large_e506e97cd2806df33fad5d2ee3e7700d.jpg",
    },
    {
        name: "The Grand Teton Loop Trail",
        description: " The Grand Teton Loop Trail is a 34.3 mile moderately trafficked loop trail located near Moose, Wyoming that features a lake and is rated as difficult. The trail is primarily used for hiking, camping, bird watching, and backpacking and is best used from March until October.",
        location: "Grand Teton Nathional Park, WY",
        length: 34.3,
        elevation: 7060,
        style: "Loop",
        difficulty: 5,
        image: "https://cdn-assets.alltrails.com/uploads/photo/image/21350314/extra_large_57f931045f8e7bbfd523c8cdd59d1398.jpg",
    },
    {
        name: "Lands End Trail",
        description: "Lands End Trail is a 3.4 mile heavily trafficked loop trail located near San Francisco, California that features beautiful wild flowers and is rated as moderate. The trail is primarily used for hiking, walking, running, and nature trips and is accessible year-round. Dogs are also able to use this trail but must be kept on leash.",
        location: "San Fransisco, CA",
        length: 3.4,
        elevation: 538,
        style: "Loop",
        difficulty: 2,
        image: "https://cdn-assets.alltrails.com/uploads/photo/image/35485447/extra_large_550cbb6219c8ce94ed5725fb9a5cdb22.jpg",
    },
    {
        name: "Bay Area Ridge Trail",
        description: "Bay Area Ridge Trail: The Golden Gate Bridge to Marin Headlands is a 1.7 mile heavily trafficked point-to-point trail located near San Francisco, California that offers the chance to see wildlife and is good for all skill levels. The trail offers a number of activity options and is accessible year-round.",
        location: "San Fransisco, CA",
        length: 1.7,
        elevation: 239,
        style: "Point to point",
        difficulty: 1,
        image: "https://cdn-assets.alltrails.com/uploads/photo/image/25424053/extra_large_b3e2978d1981193c1626ab442ee4f227.jpg",
    },
    {
        name: "Mount Washington via Tuckerman Ravine and Lion Head Trail",
        description: "Mount Washington via Tuckerman Ravine and Lion Head Trail is a 7.4 mile heavily trafficked out and back trail located near Gorham, New Hampshire that features a waterfall and is only recommended for very experienced adventurers. The trail is primarily used for hiking and is best used from June until October. Dogs are also able to use this trail.",
        location: "Mount Washington National Park, NH",
        length: 7.4,
        elevation: 4242,
        style: "Out & back",
        difficulty: 5,
        image: "https://cdn-assets.alltrails.com/uploads/photo/image/27847088/extra_large_1298ca7276cd16d4cdf7233825bd06c0.jpg",
    },
    {
        name: "Sugarload Peak",
        description: "Sugarloaf Peak is a 5.4 mile lightly trafficked out and back trail located near Sun Valley, Nevada that features beautiful wild flowers and is rated as moderate. The trail is primarily used for hiking, running, and bird watching.",
        location: "Sun Valley, NV",
        length: 5.4,
        elevation: 793,
        style: "Out & back",
        difficulty: 3,
        image: "https://cdn-assets.alltrails.com/uploads/photo/image/31345536/extra_large_1ce3d67be480f505ef8dec8edfdebdc8.jpg",
    },
    {
        name: "Batteries to Bluffs",
        description: "Batteries to Bluffs Trail is a 2.2 mile heavily trafficked loop trail located near San Francisco, California that features beautiful wild flowers and is good for all skill levels. The trail offers a number of activity options and is accessible year-round.",
        location: "San Fransisco, CA",
        length: 2.2,
        elevation: 449,
        style: "Loop",
        difficulty: 1,
        image: "https://photos.alltrails.com/eyJidWNrZXQiOiJhc3NldHMuYWxsdHJhaWxzLmNvbSIsImtleSI6InVwbG9hZHMvcGhvdG8vaW1hZ2UvMTEzNDIzMTYvNzVhNGM0OThiZjk4ODQ4M2Y0ZTllN2QxYThhNjVlYzcuanBnIiwiZWRpdHMiOnsidG9Gb3JtYXQiOiJqcGVnIiwicmVzaXplIjp7IndpZHRoIjoyMDQ4LCJoZWlnaHQiOjIwNDgsImZpdCI6Imluc2lkZSJ9LCJyb3RhdGUiOm51bGwsImpwZWciOnsidHJlbGxpc1F1YW50aXNhdGlvbiI6dHJ1ZSwib3ZlcnNob290RGVyaW5naW5nIjp0cnVlLCJvcHRpbWlzZVNjYW5zIjp0cnVlLCJxdWFudGlzYXRpb25UYWJsZSI6M319fQ==",   
    },
    {
        name: "Creeks to Peaks",
        description: "Creeks to Peaks Trail is a 3.8 mile moderately trafficked loop trail located near San Francisco, California that features beautiful wild flowers and is rated as moderate. The trail is primarily used for hiking, running, and nature trips. Dogs are also able to use this trail but must be kept on leash.",
        location: "San Fransisco, CA",
        length: 3.8,
        elevation: 725,
        style: "Loop",
        difficulty: 2,
        image: "https://photos.alltrails.com/eyJidWNrZXQiOiJhc3NldHMuYWxsdHJhaWxzLmNvbSIsImtleSI6InVwbG9hZHMvcGhvdG8vaW1hZ2UvMTU4NjkxOTkvYTgwMTIxNmE2NzY3MTdlMGM3ODgwZGI2ODQ4ZmMxNjcuanBnIiwiZWRpdHMiOnsidG9Gb3JtYXQiOiJqcGVnIiwicmVzaXplIjp7IndpZHRoIjoyMDQ4LCJoZWlnaHQiOjIwNDgsImZpdCI6Imluc2lkZSJ9LCJyb3RhdGUiOm51bGwsImpwZWciOnsidHJlbGxpc1F1YW50aXNhdGlvbiI6dHJ1ZSwib3ZlcnNob290RGVyaW5naW5nIjp0cnVlLCJvcHRpbWlzZVNjYW5zIjp0cnVlLCJxdWFudGlzYXRpb25UYWJsZSI6M319fQ==",
        coords: [37.7361000, -122.4397800],
    },
    {
        name: "Presidio Loop Trail",
        description: "Presidio Loop Trail is a 6.1 mile heavily trafficked loop trail located near San Francisco, California that features beautiful wild flowers and is rated as moderate. The trail offers a number of activity options and is accessible year-round. Dogs are also able to use this trail but must be kept on leash.",
        location: "San Fransisco, CA",
        length: 6.1,
        elevation: 777,
        style: "Loop",
        difficulty: 3,
        image: "https://photos.alltrails.com/eyJidWNrZXQiOiJhc3NldHMuYWxsdHJhaWxzLmNvbSIsImtleSI6InVwbG9hZHMvcGhvdG8vaW1hZ2UvMTk4MDUxMTMvZDcxNzc1ZDFjMWRjYzU0Y2NlMTA4YzE1N2Y1ZDIyMmYuanBnIiwiZWRpdHMiOnsidG9Gb3JtYXQiOiJqcGVnIiwicmVzaXplIjp7IndpZHRoIjoyMDQ4LCJoZWlnaHQiOjIwNDgsImZpdCI6Imluc2lkZSJ9LCJyb3RhdGUiOm51bGwsImpwZWciOnsidHJlbGxpc1F1YW50aXNhdGlvbiI6dHJ1ZSwib3ZlcnNob290RGVyaW5naW5nIjp0cnVlLCJvcHRpbWlzZVNjYW5zIjp0cnVlLCJxdWFudGlzYXRpb25UYWJsZSI6M319fQ==",
        coords: [37.7899300, -122.4596400],
    },
    {
        name: "Weltch Dickey Loop Trail",
        description: "Welch-Dickey Loop Trail is a 4.4 mile heavily trafficked loop trail located near Thornton, New Hampshire that features a great forest setting and is rated as difficult. The trail is primarily used for hiking and is best used from May until October. Dogs are also able to use this trail but must be kept on leash.",
        location: "Thorton, NH",
        length: 4.4,
        elevation: 1778,
        style: "Loop",
        difficulty: 4,
        image: "https://cdn-assets.alltrails.com/uploads/photo/image/29436638/extra_large_a4c6f59770806b1991e8c2ab8e6b5c74.jpg",
        coords: [43.9042600, -71.5886200],   
    },
    {
        name: "Owl Head Lookout",
        description: "Owl Head Lookout is a 4.9 mile lightly trafficked out and back trail located near Elizabethtown, New York that offers the chance to see wildlife and is rated as moderate. The trail is primarily used for hiking and running and is best used from April until October. Dogs are also able to use this trail but must be kept on leash.",
        location: "Elizbethtown, NY",
        length: 4.9,
        elevation: 1240,
        style: "Out & back",
        difficulty: 3,
        image: "https://photos.alltrails.com/eyJidWNrZXQiOiJhc3NldHMuYWxsdHJhaWxzLmNvbSIsImtleSI6InVwbG9hZHMvcGhvdG8vaW1hZ2UvNDE1Nzc0NDQvMTJmMDU3YzY5ODAyYjY1Mzk5MTMwMWQwOWUzZDQxY2EuanBnIiwiZWRpdHMiOnsidG9Gb3JtYXQiOiJqcGVnIiwicmVzaXplIjp7IndpZHRoIjoyMDQ4LCJoZWlnaHQiOjIwNDgsImZpdCI6Imluc2lkZSJ9LCJyb3RhdGUiOm51bGwsImpwZWciOnsidHJlbGxpc1F1YW50aXNhdGlvbiI6dHJ1ZSwib3ZlcnNob290RGVyaW5naW5nIjp0cnVlLCJvcHRpbWlzZVNjYW5zIjp0cnVlLCJxdWFudGlzYXRpb25UYWJsZSI6M319fQ==",
        coords: [44.2123400, -73.6789300],
    },
    {
        name: "Pemigewasset River Trail",
        description: "Pemigewasset River Trail is a 2.1 mile out and back trail located near Lincoln, New Hampshire that features a river and is good for all skill levels. The trail is primarily used for hiking, nature trips, and snowshoeing.",
        location: "Lincoln, NH",
        length: 2.1,
        elevation: 154,
        style: "Out & back",
        difficulty: 1,
        image: "https://cdn-assets.alltrails.com/uploads/photo/image/22421788/extra_large_dd0baa406a9973614db7e97bd3b56bbe.jpg", 
        coords: [44.0414800, -71.6636800],  
    },
];

const seedTrails = async function seedTrails () {
    try {
        await Trail.deleteMany({});
        await Review.deleteMany({});
        const createdTrails = await Trail.insertMany(trails);
        console.log("=== Trails Seeded ===");
        console.log(createdTrails);
        process.exit();
    } catch (error) {
        console.log(error);
    }
}

seedTrails();